import type { ColumnDef } from './types';

export const BASE_COLUMNS: ColumnDef[] = [
  { key: 'engine', label: 'Engine', className: 'engine-cell' },
  {
    key: 'score',
    label: 'Score',
    numeric: true,
    title:
      'Total score: geometric mean of visible benchmarks. Higher is better (inversely proportional to runtime)',
  },
  { key: 'binary_size', label: 'Binary', numeric: true, title: 'Binary size' },
  {
    key: 'loc',
    label: 'LOC',
    numeric: true,
    title: 'Lines of code: core engine code only, excluding blank lines, comments, tests and third-party code',
  },
  { key: 'language', label: 'Language', title: 'Main programming language' },
  { key: 'jit', label: 'JIT', title: 'Just-in-time compilation' },
  { key: 'years', label: 'Years', title: 'Years of active development' },
  { key: 'standard', label: 'Target', title: 'Target ECMAScript specification version' },
  { key: 'es1', label: 'ES1', numeric: true, title: 'ES1 test suite pass rate', defaultHidden: true },
  { key: 'es3', label: 'ES3', numeric: true, title: 'ES3 test suite pass rate', defaultHidden: true },
  { key: 'es5', label: 'ES5', numeric: true, title: 'ES5 test suite pass rate', defaultHidden: true },
  { key: 'es1-es5', label: 'ES1-5', numeric: true, title: 'ES1-ES5 test suite pass rate' },
  { key: 'kangax-es6', label: 'ES6', numeric: true, title: "compat-table's ES6 conformance score" },
  {
    key: 'kangax-es2016plus',
    label: 'ES2016+',
    numeric: true,
    title: "compat-table's ES2016+ conformance score",
  },
  { key: 'kangax-es2016', label: 'ES2016', numeric: true, title: "compat-table's ES2016 conformance score", defaultHidden: true },
  { key: 'kangax-es2017', label: 'ES2017', numeric: true, title: "compat-table's ES2017 conformance score", defaultHidden: true },
  { key: 'kangax-es2018', label: 'ES2018', numeric: true, title: "compat-table's ES2018 conformance score", defaultHidden: true },
  { key: 'kangax-es2019', label: 'ES2019', numeric: true, title: "compat-table's ES2019 conformance score", defaultHidden: true },
  { key: 'kangax-es2020', label: 'ES2020', numeric: true, title: "compat-table's ES2020 conformance score", defaultHidden: true },
  { key: 'kangax-es2021', label: 'ES2021', numeric: true, title: "compat-table's ES2021 conformance score", defaultHidden: true },
  { key: 'kangax-es2022', label: 'ES2022', numeric: true, title: "compat-table's ES2022 conformance score", defaultHidden: true },
  { key: 'kangax-es2023', label: 'ES2023', numeric: true, title: "compat-table's ES2023 conformance score", defaultHidden: true },
  { key: 'kangax-es2024', label: 'ES2024', numeric: true, title: "compat-table's ES2024 conformance score", defaultHidden: true },
  { key: 'kangax-es2025', label: 'ES2025', numeric: true, title: "compat-table's ES2025 conformance score", defaultHidden: true },
  { key: 'kangax-intl', label: 'ESIntl', numeric: true, title: "compat-table's ES Intl conformance score", defaultHidden: true },
  { key: 'kangax-next', label: 'ESNext', numeric: true, title: "compat-table's ESNext conformance score", defaultHidden: true },
  { key: 'github_stars', label: 'Stars', numeric: true, title: 'GitHub stars' },
  { key: 'github_contributors', label: 'Contributors', numeric: true, title: 'GitHub contributors count' },
  { key: 'org', label: 'Org' },
  { key: 'license', label: 'License', className: 'license-cell' },
  { key: 'description', label: 'Description', className: 'description-cell' },
  { key: 'interpreter', label: 'Interpreter', title: 'Interpreter/bytecode mode availability', defaultHidden: true },
  { key: 'type', label: 'Type', title: 'Engine type (VM, compiler, interpreter)', defaultHidden: true },
  { key: 'platform', label: 'Platform', title: 'Supported platforms/targets', defaultHidden: true },
  { key: 'features', label: 'Features', title: 'Notable engine features', defaultHidden: true },
  { key: 'regex', label: 'Regex', title: 'Regular expression engine details', defaultHidden: true },
];

export const BENCHMARK_COLUMNS: ColumnDef[] = [
  {
    key: 'Richards',
    label: 'Richards',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'Richards: task scheduler simulator, property access benchmark',
  },
  {
    key: 'DeltaBlue',
    label: 'DeltaBlue',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'DeltaBlue: constraint solver, polymorphism benchmark',
  },
  {
    key: 'Crypto',
    label: 'Crypto',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'Crypto: RSA encryption, integer math, bit operations and arrays benchmark',
  },
  {
    key: 'RayTrace',
    label: 'RayTrace',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'RayTracer: floating-point math and objects benchmark',
  },
  {
    key: 'EarleyBoyer',
    label: 'EarleyBoyer',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'EarleyBoyer: scheme interpreter, memory/GC and variadic functions benchmark',
  },
  {
    key: 'RegExp',
    label: 'RegExp',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'Regexp: RE, strings and arrays benchmark',
  },
  {
    key: 'Splay',
    label: 'Splay',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'Splay: memory/GC benchmark',
  },
  {
    key: 'SplayLatency',
    label: 'SplayLatency',
    numeric: true,
    benchmark: true,
    title: 'SplayLatency: GC latency',
  },
  {
    key: 'NavierStokes',
    label: 'NavierStokes',
    numeric: true,
    benchmark: true,
    v8: true,
    title: 'NavierStokes: fluid simulation, floating-point math and arrays benchmark',
  },
  {
    key: 'PdfJS',
    label: 'PdfJS',
    numeric: true,
    benchmark: true,
    title: 'PdfJS: real-world PDF.js parser, bit operations and arrays benchmark',
  },
  {
    key: 'Mandreel',
    label: 'Mandreel',
    numeric: true,
    benchmark: true,
    title: 'Mandreel: C++ physics engine',
  },
  {
    key: 'MandreelLatency',
    label: 'MandreelLatency',
    numeric: true,
    benchmark: true,
    title: 'MandreelLatency: compilation latency',
  },
  {
    key: 'Gameboy',
    label: 'Gameboy',
    numeric: true,
    benchmark: true,
    title: 'Gameboy: GB emulator, typed arrays and property access performance benchmark',
  },
  {
    key: 'CodeLoad',
    label: 'CodeLoad',
    numeric: true,
    benchmark: true,
    title: 'CodeLoad: jQuery and Closure load speed benchmark',
  },
  {
    key: 'Box2D',
    label: 'Box2D',
    numeric: true,
    benchmark: true,
    title: 'Box2D: C physics engine',
  },
  {
    key: 'zlib',
    label: 'zlib',
    numeric: true,
    benchmark: true,
    title: 'zlib: Emscripten/asm.js benchmark',
  },
  {
    key: 'Typescript',
    label: 'Typescript',
    numeric: true,
    benchmark: true,
    title:
      'Typescript: TS compiler running on itself, benchmarks speed of optimizing a large pile of code',
  },
];

export const ALL_COLUMNS: ColumnDef[] = [...BASE_COLUMNS, ...BENCHMARK_COLUMNS];
